# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

PrelaunchSignup:
  fields:
    default: email, winery
    form: email, winery
  order_by: 
  relationships: 
  filters: 
  search: 
  application: socialwino

User:
  fields:
    default: name, username, email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip, admin
    form: name, username, email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip, admin
  order_by: 
  relationships: 
  filters: 
  search: name
  application: socialwino

